DATA_DIR: "/users/broderick/mnt/Acadia/Projects/spatial_frequency_preferences/BIDS"
MRI_TOOLS: "/users/broderick/Documents/MRI_tools"
FREESURFER_DIR: "/share/apps/freesurfer/6.0.0"
GLMDENOISE_PATH: "/home/wfb229/matlab-toolboxes/GLMdenoise"
WORKING_DIR: "/users-local/broderick/preprocess"
