DATA_DIR: "/scratch/wfb229/spatial_frequency_preferences"
MRI_TOOLS: "/home/wfb229/MRI_tools"
FREESURFER_DIR: "/share/apps/freesurfer/6.0.0"
GLMDENOISE_PATH: "/home/wfb229/matlab-toolboxes/GLMdenoise"
