DATA_DIR: "/users/broderick/mnt/winawerlab/Projects/spatial_frequency_preferences/BIDS"
MRI_TOOLS: "/users/broderick/Documents/MRI_tools"
FREESURFER_DIR: "/share/apps/freesurfer/6.0.0"
GLMDENOISE_PATH: "/users/broderick/Documents/MATLAB/toolboxes/GLMdenoise"
WORKING_DIR: "/users-local/broderick/preprocess"
VISTASOFT_PATH: "/users/broderick/Documents/MATLAB/toolboxes/vistasoft"
TESLA_DIR: "/mnt/Tesla/spatial_frequency_preferences"
EXTRA_FILES_DIR: "/mnt/winawerlab/Projects/spatial_frequency_preferences/extra_files"
SUBJECTS_DIR: "/users/broderick/mnt/winawerlab/Freesurfer_subjects"
RETINOTOPY_DIR: "/users/broderick/mnt/winawerlab/Projects/Retinotopy/BIDS"
