DATA_DIR: "/mnt/prince_scratch/spatial_frequency_preferences"
MRI_TOOLS: "/home/billbrod/Documents/MRI_tools"
FREESURFER_DIR: "/share/apps/freesurfer/6.0.0"
GLMDENOISE_PATH: "/home/wfb229/matlab-toolboxes/GLMdenoise"
WORKING_DIR: "/users-local/broderick/preprocess"
VISTASOFT_PATH: "/home/wfb229/matlab-toolboxes/vistasoft"
TESLA_DIR: "/mnt/Tesla/spatial_frequency_preferences"
EXTRA_FILES_DIR: "/mnt/winawerlab/Projects/spatial_frequency_preferences/extra_files"
