name: sfp
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.6.3
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - statsmodels
  - pandas
  - pyyaml
  - nipype>=1.1.1
  - pillow
  - pyosf
  - osfclient
  - h5py
  - nibabel
  - scikit-learn
  - snakemake>=5.4
  - pip:
      - pybids >= 0.7.0
      - neuropythy >= 0.9.0
      - pytest
      # this is just forked from the original repo, from mariogeiger,
      # but since that didn't have any release tags, I forked to make
      # sure the version I use stays constant
      - git+https://github.com/billbrod/hessian.git@master#egg=hessian
