name: sfp
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.6.3
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib==3.0.3
  - scipy
  - seaborn>=0.11
  - statsmodels
  - pandas>=0.25
  - pyyaml
  - nipype>=1.1.1
  - pillow
  - h5py
  - nibabel
  - scikit-learn
  - snakemake>=5.4
  - tqdm
  - pip:
      - pybids == 0.8.0
      - neuropythy >= 0.9.0
      # this is just forked from the original repo, from mariogeiger,
      # but since that didn't have any release tags, I forked to make
      # sure the version I use stays constant
      - git+https://github.com/billbrod/hessian.git@master#egg=hessian
      - pyrtools
      - torch==1.1
      - svgutils
